POST http://localhost:3001/survey-manager/apis/admin/surveys HTTP/1.1
Content-Type: application/json

{
    "title":"Ice cream survey",
    "description":"A simple survey to assess if people like ice cream.",
    "isPublished":true,
    "estCompletionMinutes":7
}
