POST http://localhost:3001/survey-manager/apis/admin/surveys/14/questions HTTP/1.1
Content-Type: application/json

# {
#         "position": 1,
#         "title":"Do you like ice cream?",
#         "type":"OPEN",
#         "isOptional":false, 
#         "maxAnswerLength":200
# }

{
        "position":2,
        "title":"What flavor do you fancy?",
        "type":"MULTIPLE_CHOICE",
        "minChoices":0,
        "maxChoices":1,
        "options": ["Strawberry", "Blackberry"]
    }